import type { MetadataRoute } from "next";

// P14 — web app manifest (installability + the Android TWA prerequisite). Next
// serves this at /manifest.webmanifest and injects <link rel="manifest">. Icons
// are generated by scripts/gen-icons.mjs (the real brand mark as of 2026-07-27
// — re-run the script after any further art change).
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Fandex",
    short_name: "Fandex",
    description: "Your personal index of games, movies, and shows — wishlists, taste-based discovery, and a release calendar.",
    start_url: "/",
    display: "standalone",
    // Ticket · Calm's real surface token (H1.6a) — this file was missed when
    // layout.tsx's viewport.themeColor was updated, same class of bug as the
    // item-detail page's hardcoded #0a0a0a (2026-07-27).
    background_color: "#100E0C",
    theme_color: "#100E0C",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
