import type { MetadataRoute } from "next";

// P14 — web app manifest (installability + the Android TWA prerequisite). Next
// serves this at /manifest.webmanifest and injects <link rel="manifest">. Icons
// are generated by scripts/gen-icons.mjs (placeholder radar art — swap for real
// brand art anytime and re-run the script).
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "ReleaseRadar",
    short_name: "ReleaseRadar",
    description: "One calendar for every game, movie, and show you're waiting for.",
    start_url: "/",
    display: "standalone",
    background_color: "#0a0a0a",
    theme_color: "#0a0a0a",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
